### ISSUE TITLE
latest release v0.6.2 windows build is not latest

### ISSUE THREAD

**Issue by vickey58** [aktau/github-release#44] opened 2016-04-01 14:15 UTC
Hi I downloaded the the latest release v0.6.2 windows build(**windows-amd64-github-release.zip**) and run the command to create git TAG from a branch using command release with parameter --target.
following is my command
github-release release --user ${GITHUB_ORGANIZATION} --repo ${GITHUB_REPO}--${VERSION_NAME} --name ${VERSION_NAME} --description "bla bla bla" --target ${BRANCH_NAME}

**Comment by neurosnap** [comment] 2016-10-07 18:33
I'm running into the same issue with the linux build.

**Comment by aktau** [comment] 2017-03-26 18:00
This is very strange. So a build that was marked as v0.6.2 did not have the option? Maybe something is wrong with my makefile. Anyway, does the current latest build show the problem?

**Comment by aktau** [comment] 2017-03-27 08:10
I see what the problem is... the `make release` command does not clean old binaries, it re-uses them if they're already present. That's stupid, I'll get that fixed when I'm near a usable computer.

**Closed** 2017-03-29 20:24 UTC
